# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.2"
manifest_format = "2.0"
project_hash = "412de5005ff3798c8a85fbb7a19202e39cd7c028"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.EasyMonad]]
deps = ["MacroTools", "MonadInterface"]
git-tree-sha1 = "251e368fe9379aef3c0eacf6c23a24be6104ffe3"
repo-rev = "main"
repo-url = "https://github.com/JuliaHybrid/EasyMonad.jl.git"
uuid = "e4dbf12b-b8cf-4673-b6eb-8b0d4667dd49"
version = "0.1.0"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "42324d08725e200c23d4dfb549e0d5d89dede2d2"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.10"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MonadInterface]]
git-tree-sha1 = "7e4db9bbbae34fafd2e4a8784e9755d8524ba299"
repo-rev = "main"
repo-url = "https://github.com/JuliaHybrid/MonadInterface.jl.git"
uuid = "4c81018e-a0fd-4a0d-a53b-43c59f4db333"
version = "0.1.0"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
